package dev.hari.body;
import android.Manifest;import android.app.Activity;import android.content.*;import android.content.pm.PackageManager;import android.media.projection.MediaProjectionManager;import android.os.*;import android.provider.Settings;import android.view.View;import android.widget.*;
public final class MainActivity extends Activity{
    private static final int REQUEST_SCREEN=1001;private TextView status;
    @Override protected void onCreate(Bundle state){super.onCreate(state);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},10);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);int pad=(int)(20*getResources().getDisplayMetrics().density);root.setPadding(pad,pad,pad,pad);status=new TextView(this);status.setText("HARI body: sensors are off until you enable them.");root.addView(status);Button a=button("Enable semantic screen access");a.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));root.addView(a);Button p=button("Allow on-demand screenshots");p.setOnClickListener(v->{MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);startActivityForResult(m.createScreenCaptureIntent(),REQUEST_SCREEN);});root.addView(p);Button c=button("Capture one screen frame");c.setOnClickListener(v->startService(new Intent(this,ScreenProjectionService.class).setAction(ScreenProjectionService.ACTION_CAPTURE_ONCE)));root.addView(c);Button r=button("Show last observation");r.setOnClickListener(this::showLastObservation);root.addView(r);setContentView(root);}
    private Button button(String text){Button b=new Button(this);b.setText(text);return b;}
    private void showLastObservation(View ignored){Observation o=ObservationBus.latest();status.setText(o==null?"No observation yet.":o.kind()+" from "+o.source()+"\ntrusted as instruction: "+o.trustedAsInstruction()+"\n"+o.payload());}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=REQUEST_SCREEN||resultCode!=RESULT_OK||data==null)return;Intent s=new Intent(this,ScreenProjectionService.class).setAction(ScreenProjectionService.ACTION_START).putExtra(ScreenProjectionService.EXTRA_RESULT_CODE,resultCode).putExtra(ScreenProjectionService.EXTRA_RESULT_DATA,data);startForegroundService(s);}
}
